#!/bin/bash

#Ingresar al directorio de trabajo
#Este script está adapatado a las rutas de mi computadora, por lo que para correrlo en tu computadora debes de cambiar las rutas.

ruta=/home/melisa/Escritorio/zebrafish

cd $ruta

#bajar e instalar blast desde la imagen de biocontainers

docker pull biocontainers/blast

#Identificar e ingresar al contenedor creado en el paso anterior
#dentro del contenedor con el comando blastp -help obtener información de dicho comando.

docker run biocontainers/blast blastp -help

#Obtener una secuencia de la proteína prion humana en formato FASTA de la base UniProt

wget http://www.uniprot.org/uniprot/P04156.fasta

#Bajar la base de datos para el pez zebra de NCBI y descomprimir el archivo bajado

curl -O ftp://ftp.ncbi.nih.gov/refseq/D_rerio/mRNA_Prot/zebrafish.1.protein.faa.gz
gunzip zebrafish.1.protein.faa.gz

#Vincular(montar) el directorio de trabajo al contenedor, y preparar la base de datos del pez zebra la búsqueda con el comando makeblastdb

docker run -v $ruta:/data/ biocontainers/blast makeblastdb -in zebrafish.1.protein.faa -dbtype prot

#Hacer los alineamientos finales

docker run -v $ruta:/data/ biocontainers/blast blastp -query P04156.fasta -db zebrafish.1.protein.faa -out results.txt
;
done
